config/routes.rb
Rails.application.routes.draw do
  root 'businesses#index'
  get "user", to: "users#show"
  resources :businesses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :businesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/businesses/index.html.erb
<% @businesses.each do |business| %>
  <p>
    <%= business.title %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <p class="h5 my-0 me-md-auto fw-normal"><%= link_to "Companies", businesses_path %></p>
      <nav class="my-2 my-md-0 me-md-3">
        <a class="p-2 text-dark" href="#"><%= link_to "User page", user_path %></a>
        <a class="p-2 text-dark" href="#">Enterprise</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">Pricing</a>
      </nav>
      <a class="btn btn-outline-primary" href="#">Sign up</a>
    </header>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/show.html.erb
<h1>User page</h1>
<p>Username: <%= @user.username %></p>
<h3>User orders</h3>

<% @user.businesses.each do |b| %>
  <%= b.title  %>
<% end %>